version: "3.4"

networks:
  proxynetwork:
    external: true
  net:
    driver: overlay
    attachable: true

volumes:
  mariadb_data:

services:
  mailhog:
    image: portainer/portainer-ce:2.0.1
    networks:
      - net
      - proxynetwork
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mailhog-portainer.rule=Host(`portainer.lxc`)"
        - "traefik.http.routers.mailhog-portainer.entrypoints=web"
        - "traefik.http.services.mailhog-portainer.loadbalancer.server.port=9000"